name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    services:
      mariadb:
        image: mariadb:11.8
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: test_db
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Create .env for tests
        run: |
          echo DB_HOST=127.0.0.1 >> .env
          echo DB_PORT=3307 >> .env
          echo DB_USER=root >> .env
          echo DB_PASSWORD=root >> .env
          echo DB_NAME=test_db >> .env
          echo AUTOCOMMIT=true >> .env

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..60}; do
            if mysqladmin ping -h127.0.0.1 -P3307 -uroot -proot --silent; then
              echo "MariaDB is up"; break; fi; sleep 2; done

      - name: Run tests with coverage
        run: |
          pytest -q --cov=src --cov-report=term-missing

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: ./.coverage
